### ISSUE TITLE
exam database seems down

### ISSUE THREAD

**Issue by jmhirsch** [ubccsss/exams#2]
Seems like the exam database can't be accessed from the links on ubccsss (https://exams.ubccsss.org)

**Comment by eqfy** [comment]
We are currently addressing the issue. Sorry for any inconvenience caused!

**Comment by eqfy** [comment]
Exam db is back online!

We will be thoroughly reviewing this incident and making sure that similar issues won't arise in the future.

**Comment by jmhirsch** [comment]
Thank you for the quick fix!
